[versions]
kotlin="2.4.0"
serialization = "1.11.1-SNAPSHOT"
testballoon = "1.0.1-K2.4.0"
asp="20260701"
agp = "8.12.3"
spotless = "8.2.1"
modulator = "0.1.0"
awesn1 = "0.6.1"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
kotlinx-serialization-cbor = { module = "org.jetbrains.kotlinx:kotlinx-serialization-cbor", version.ref = "serialization" }
#for build logic conventions plugin, as it needs the artifact, not the plugin ID
asp = { module = "at.asitplus.gradle:k2", version.ref = "asp" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
awesn1-kxs = { module = "at.asitplus.awesn1:kxs", version.ref = "awesn1" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
asp = { id = "at.asitplus.gradle.conventions", version.ref = "asp" }
modulator = { id = "at.asitplus.gradle.modulator", version.ref = "modulator" }
