name: Publish
on: workflow_dispatch
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  publish:
    runs-on: macos-latest
    timeout-minutes: 300
    steps:
      - name: Common Setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@v3
        with:
          override-cache: 'true'
          setup-xcode: 'true'

      - name: Publish Propigator modules serially to Sonatype
        run: |
          ./gradlew clean
          ./gradlew :core:publishToSonatype closeSonatypeStagingRepository
          ./gradlew :json:publishToSonatype closeSonatypeStagingRepository
          ./gradlew :cbor:publishToSonatype closeSonatypeStagingRepository
          ./gradlew :multi:publishToSonatype closeSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.PUBLISH_SIGNING_KEYID }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PUBLISH_SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PUBLISH_SIGNING_PASSWORD }}
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.PUBLISH_SONATYPE_USER }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.PUBLISH_SONATYPE_PASSWORD }}
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Common Setup
        uses: a-sit-plus/internal-workflows/.github/actions/common-setup@v3
        with:
          override-cache: 'false'
      - name: Build Dokka HTML
        run: ./gradlew dokkaGenerate
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload docs folder
          path: './build/docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
